name: auto-deploy with docker

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Git 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: JDK 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      #     - name: application.yml 복사 (필요 시 주석 해제)
      #       run: cp 경로/application.yml ./src/main/resources/application.yml

      - name: 애플리케이션 빌드
        run: chmod +x ./gradlew && ./gradlew clean build

      - name: Docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USER }}/web-app:latest .

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USER }}/web-app:latest

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name: EC2 서버에 SSH 접속 및 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            docker stop myweb || true
            docker rm myweb || true
            docker pull ${{ secrets.DOCKER_USER }}/web-app:latest
            docker run -d --name myweb -p 8080:8080 ${{ secrets.DOCKER_USER }}/web-app:latest
